spring:
  config:
    activate:
      on-profile: local
  #h2 database connection details
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update  # Automatically update the schema (create, validate, update, none)
  h2:
    console:
      enabled: true  # Enable the H2 console for web access
  sql:
    init:
      platform: h2
server:
  port: 8081
#Authenticating API with below User Details
auth:
  username: katatest
  password: katatest@123
#allowing call come from React App
allowed-origin: "http://localhost:3000"
#Logging setting
logging:
  level:
    root: INFO                # Default logging level for all packages
  file:
    name: logs/app.log        # Log file name and location
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"   # Console log pattern
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"  # File log pattern