###
GET http://localhost:8081/api/v1/books

<> 2025-06-22T122102.404.json

### Autherization id is just for testing,Remove it from Higher environemt application
GET http://localhost:8081/api/v1/books
Authorization: Basic a2F0YXRlc3Q6a2F0YXRlc3RAMTIz



