###
POST http://localhost:8081/api/v1/cart/add?
    bookId=2&
    quantity=2
Authorization: Basic

###  non existing bookId
POST http://localhost:8081/api/v1/cart/add?
    bookId=2&
    quantity=1

###
DELETE http://localhost:8081/api/v1/cart/items/1
Authorization: Basic

### non existing Id
DELETE http://localhost:8081/api/v1/cart/items/4
Authorization: Basic


###
PUT http://localhost:8081/api/v1/cart/items/1?quantity=4
Authorization: Basic




